import * as THREE from 'https://cdn.jsdelivr.net/npm/three@0.160.1/build/three.module.js';
import {OrbitControls} from 'https://cdn.jsdelivr.net/npm/three@0.160.1/examples/jsm/controls/OrbitControls.js';
const canvas=document.getElementById('view'),loader=document.getElementById('loader'),statusEl=document.getElementById('status'),poseEl=document.getElementById('poseSliders'),morphEl=document.getElementById('morphSliders'),catsEl=document.getElementById('cats');
let scene,camera,renderer,controls,rig,model,guides,labels,parts={},pose={yaw:0,pitch:0,roll:0},cat='All';
let m={brow:0,eye:0,nose:0,cheek:0,mouth:0,jaw:0,chin:0,ear:0};
const groups={All:Object.keys(m),Brows:['brow'],Eyes:['eye'],Nose:['nose'],Mouth:['mouth','jaw'],Cheek:['cheek','chin','ear']};
const names={brow:'Eyebrows',eye:'Eyes / eyelids',nose:'Nose length',cheek:'Cheek width',mouth:'Mouth / smile',jaw:'Jaw drop',chin:'Chin forward',ear:'Ear size'};
init();build();loader.classList.add('hide');statusEl.innerHTML='<span class="ok">Fallback עובד: ראש מקומי נטען בלי שרת חיצוני. זה לא המודל הסופי, אבל עכשיו יש ראש, צוואר, קווי Loomis תלת־ממדיים וסליידרים בסיסיים.</span>';
function init(){renderer=new THREE.WebGLRenderer({canvas,antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.setSize(innerWidth,innerHeight);scene=new THREE.Scene();scene.background=new THREE.Color(0x10141a);camera=new THREE.PerspectiveCamera(35,innerWidth/innerHeight,.01,100);camera.position.set(0,.8,2.6);scene.add(new THREE.HemisphereLight(0xffffff,0x283040,2));let l=new THREE.DirectionalLight(0xffffff,2.5);l.position.set(2,3,4);scene.add(l);rig=new THREE.Group();scene.add(rig);model=new THREE.Group();guides=new THREE.Group();labels=new THREE.Group();rig.add(model,guides,labels);controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=true;controls.target.set(0,.75,0);addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight)});document.querySelectorAll('[data-camera]').forEach(b=>b.onclick=()=>cam(b.dataset.camera));document.querySelectorAll('[data-preset]').forEach(b=>b.onclick=()=>preset(b.dataset.preset));resetBtn.onclick=reset;guidesBtn.onclick=()=>{guides.visible=!guides.visible;guidesBtn.classList.toggle('on',guides.visible)};edgeBtn.onclick=()=>edgeBtn.classList.toggle('on');labelBtn.onclick=()=>{labels.visible=!labels.visible;labelBtn.classList.toggle('on',labels.visible)};guidesBtn.classList.add('on');edgeBtn.classList.add('on');labelBtn.classList.add('on');poseUI();catsUI();requestAnimationFrame(loop)}
function loop(){requestAnimationFrame(loop);controls.update();renderer.render(scene,camera)}
function material(c){return new THREE.MeshStandardMaterial({color:c,roughness:.75,metalness:0,flatShading:true})}
function add(n,g,c,p,s){let o=new THREE.Mesh(g,material(c));o.position.set(...p);o.scale.set(...s);model.add(o);parts[n]=o;let e=new THREE.LineSegments(new THREE.EdgesGeometry(g,15),new THREE.LineBasicMaterial({color:0x111111,transparent:true,opacity:.45}));o.add(e);return o}
function build(){let head=new THREE.SphereGeometry(.55,8,8);head.scale(.78,1.1,.62);add('head',head,0xbfc7cf,[0,1.05,0],[1,1,1]);add('neck',new THREE.CylinderGeometry(.18,.25,.65,6),0x565e6b,[0,.22,0],[1,1,1]);add('shoulder',new THREE.CylinderGeometry(.75,.9,.18,6),0x565e6b,[0,-.15,0],[1,.35,.5]);add('jaw',new THREE.BoxGeometry(.55,.28,.18),0xbfc7cf,[0,.55,.34],[1,1,1]);add('chin',new THREE.BoxGeometry(.25,.16,.14),0xbfc7cf,[0,.36,.46],[1,1,1]);add('eyeL',new THREE.SphereGeometry(.07,10,6),0xf2f5f7,[-.2,1.13,.51],[1.3,.55,.35]);add('eyeR',new THREE.SphereGeometry(.07,10,6),0xf2f5f7,[.2,1.13,.51],[1.3,.55,.35]);add('browL',new THREE.BoxGeometry(.22,.05,.03),0x2f3338,[-.22,1.27,.53],[1,1,1]);add('browR',new THREE.BoxGeometry(.22,.05,.03),0x2f3338,[.22,1.27,.53],[1,1,1]);add('nose',new THREE.ConeGeometry(.12,.34,4),0xbfc7cf,[0,.94,.61],[.85,1,1]).rotation.x=Math.PI/2;add('mouth',new THREE.BoxGeometry(.32,.035,.03),0x514338,[0,.66,.57],[1,1,1]);add('open',new THREE.BoxGeometry(.22,.1,.035),0x20252c,[0,.62,.59],[1,.05,1]);add('earL',new THREE.TorusGeometry(.1,.023,6,12),0xbfc7cf,[-.52,1.02,0],[.7,1.1,.25]).rotation.y=Math.PI/2;add('earR',new THREE.TorusGeometry(.1,.023,6,12),0xbfc7cf,[.52,1.02,0],[.7,1.1,.25]).rotation.y=Math.PI/2;loomis();morphUI();cam('front')}
function lm(c){return new THREE.LineBasicMaterial({color:c,depthTest:false})}function line(a,c){return new THREE.Line(new THREE.BufferGeometry().setFromPoints(a.map(p=>new THREE.Vector3(...p))),lm(c))}function ellipse(rx,ry,z,y,c){let p=[];for(let i=0;i<80;i++){let t=i/79*Math.PI*2;p.push(new THREE.Vector3(Math.cos(t)*rx,y+Math.sin(t)*ry,z))}return new THREE.Line(new THREE.BufferGeometry().setFromPoints(p),lm(c))}
function loomis(){guides.add(ellipse(.44,.53,.55,1.08,0x57c9ff));guides.add(line([[0,1.55,.57],[0,.35,.57]],0xff78a0));[['hair',1.33,0x5af096],['brow',1.18,0x5af096],['eyes',1.10,0xffd66f],['nose',.88,0x5af096],['mouth',.70,0xffd66f],['chin',.48,0x5af096]].forEach(([n,y,c])=>guides.add(line([[-.38,y,.58],[.38,y,.58]],c)));guides.add(ellipse(.18,.43,.02,1.06,0x57c9ff))}
function slider(label,min,max,step,val,cb){let d=document.createElement('div');d.className='slider';d.innerHTML=`<div class="top"><span>${label}</span><span class="val">${val}</span></div><input type="range" min="${min}" max="${max}" step="${step}" value="${val}">`;let input=d.querySelector('input'),v=d.querySelector('.val');input.oninput=()=>{v.textContent=input.value;cb(+input.value)};return d}
function poseUI(){poseEl.innerHTML='';[['Yaw','yaw',-60,60],['Pitch','pitch',-45,45],['Roll','roll',-35,35]].forEach(x=>poseEl.appendChild(slider(x[0],x[2],x[3],1,0,v=>{pose[x[1]]=v;rig.rotation.set(THREE.MathUtils.degToRad(pose.pitch),THREE.MathUtils.degToRad(pose.yaw),THREE.MathUtils.degToRad(pose.roll))})))}
function catsUI(){catsEl.innerHTML='';Object.keys(groups).forEach(g=>{let b=document.createElement('button');b.className='tab'+(g===cat?' on':'');b.textContent=g;b.onclick=()=>{cat=g;catsUI();morphUI()};catsEl.appendChild(b)})}
function morphUI(){morphEl.innerHTML='';groups[cat].forEach(k=>morphEl.appendChild(slider(names[k],0,1,.01,m[k],v=>{m[k]=v;apply()})))}
function apply(){parts.browL.position.y=1.27+m.brow*.09;parts.browR.position.y=1.27+m.brow*.09;parts.eyeL.scale.y=parts.eyeR.scale.y=.55+m.eye*.55;parts.nose.scale.z=1+m.nose*.5;parts.nose.position.z=.61+m.nose*.08;parts.cheekL&&(parts.cheekL.position.x=-.33-m.cheek*.08);parts.mouth.scale.x=1+m.mouth*.55;parts.open.scale.y=.05+m.jaw*.95;parts.jaw.position.y=.55-m.jaw*.12;parts.chin.position.z=.46+m.chin*.15;parts.earL.scale.set(.7+m.ear*.35,1.1+m.ear*.45,.25);parts.earR.scale.set(.7+m.ear*.35,1.1+m.ear*.45,.25)}
function preset(p){Object.keys(m).forEach(k=>m[k]=0);if(p==='smile')m.mouth=.9;if(p==='blink')m.eye=0;if(p==='jaw')m.jaw=.9;apply();morphUI()}function reset(){Object.keys(m).forEach(k=>m[k]=0);pose={yaw:0,pitch:0,roll:0};rig.rotation.set(0,0,0);poseUI();morphUI();apply();cam('front')}function cam(t){let y=.8,d=2.45,mp={front:[0,y,d],threeq:[-1.1,y,2.05],profile:[-d,y,.03],up:[0,y+.55,d*.78],down:[0,y-.55,d*.78]};camera.position.set(...(mp[t]||mp.front));controls.target.set(0,.78,0);controls.update()}
