import React,{useEffect,useMemo,useRef,useState}from'react';
import{createRoot}from'react-dom/client';
import*as THREE from'three';
import{GLTFLoader}from'three/examples/jsm/loaders/GLTFLoader.js';
import'./styles.css';

const DEFAULT_MODEL='https://models.readyplayer.me/65a8dba831b23abb4f401bae.glb?morphTargets=ARKit,Oculus%20Visemes&textureAtlas=none&lod=0';
const PRESETS={neutral:{},smile:{mouthSmileLeft:.75,mouthSmileRight:.75,cheekSquintLeft:.25,cheekSquintRight:.25},angry:{browDownLeft:.8,browDownRight:.8,eyeSquintLeft:.35,eyeSquintRight:.35,mouthFrownLeft:.35,mouthFrownRight:.35},surprise:{jawOpen:.65,eyeWideLeft:.75,eyeWideRight:.75,browInnerUp:.7,browOuterUpLeft:.55,browOuterUpRight:.55},talk:{jawOpen:.45,mouthFunnel:.35,mouthPucker:.15}};

function clamp(v,a,b){return Math.max(a,Math.min(b,v))}
function findHeadBox(root){const box=new THREE.Box3();let found=false;root.traverse(o=>{if(o.isMesh){o.geometry.computeBoundingBox();const b=o.geometry.boundingBox.clone().applyMatrix4(o.matrixWorld);if(!found){box.copy(b);found=true}else box.union(b)}});return box}
function morphNames(root){const set=new Set();root.traverse(o=>{if(o.isMesh&&o.morphTargetDictionary)Object.keys(o.morphTargetDictionary).forEach(n=>set.add(n))});return [...set].sort()}
function applyMorph(root,name,value){root.traverse(o=>{if(o.isMesh&&o.morphTargetDictionary&&o.morphTargetInfluences){const i=o.morphTargetDictionary[name];if(i!==undefined)o.morphTargetInfluences[i]=value}})}

function App(){const mount=useRef(null),sceneRef=useRef(null),modelRef=useRef(null),cameraRef=useRef(null),rendererRef=useRef(null),controls=useRef({rotX:0,rotY:0,zoom:1,drag:false,last:null});const[loading,setLoading]=useState('טוען מודל...');const[err,setErr]=useState('');const[names,setNames]=useState([]);const[values,setValues]=useState({});const[overlay,setOverlay]=useState(true);const[planes,setPlanes]=useState(true);const[wire,setWire]=useState(false);const[tab,setTab]=useState('morph');
useEffect(()=>{const el=mount.current;const scene=new THREE.Scene();scene.background=new THREE.Color(0x070b16);sceneRef.current=scene;const camera=new THREE.PerspectiveCamera(35,1,.01,100);camera.position.set(0,.08,2.8);cameraRef.current=camera;const renderer=new THREE.WebGLRenderer({antialias:true,alpha:false});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.outputColorSpace=THREE.SRGBColorSpace;el.appendChild(renderer.domElement);rendererRef.current=renderer;scene.add(new THREE.HemisphereLight(0xffffff,0x223355,2.1));const key=new THREE.DirectionalLight(0xffffff,2.2);key.position.set(1.8,2.5,2.5);scene.add(key);const fill=new THREE.DirectionalLight(0x80bfff,.9);fill.position.set(-2,.5,1);scene.add(fill);
const resize=()=>{const r=el.getBoundingClientRect();renderer.setSize(r.width,r.height,false);camera.aspect=r.width/r.height;camera.updateProjectionMatrix()};new ResizeObserver(resize).observe(el);resize();
let raf;const tick=()=>{raf=requestAnimationFrame(tick);const m=modelRef.current;if(m){m.rotation.y=controls.current.rotY;m.rotation.x=controls.current.rotX;const s=controls.current.zoom;m.scale.setScalar(s)}renderer.render(scene,camera)};tick();
const c=renderer.domElement;const down=e=>{controls.current.drag=true;controls.current.last={x:e.clientX,y:e.clientY};c.setPointerCapture?.(e.pointerId)};const move=e=>{if(!controls.current.drag)return;const l=controls.current.last;controls.current.rotY+=(e.clientX-l.x)*.008;controls.current.rotX=clamp(controls.current.rotX+(e.clientY-l.y)*.008,-.9,.9);controls.current.last={x:e.clientX,y:e.clientY}};const up=()=>controls.current.drag=false;const wheel=e=>{e.preventDefault();controls.current.zoom=clamp(controls.current.zoom-e.deltaY*.001,.55,2.4)};c.addEventListener('pointerdown',down);c.addEventListener('pointermove',move);c.addEventListener('pointerup',up);c.addEventListener('wheel',wheel,{passive:false});loadModel(DEFAULT_MODEL);return()=>{cancelAnimationFrame(raf);renderer.dispose();el.innerHTML=''}},[]);
function clearModel(){const s=sceneRef.current;if(modelRef.current)s.remove(modelRef.current);modelRef.current=null}
function frame(root){root.updateMatrixWorld(true);const box=findHeadBox(root);const size=box.getSize(new THREE.Vector3());const center=box.getCenter(new THREE.Vector3());root.position.sub(center);const max=Math.max(size.x,size.y,size.z)||1;root.scale.setScalar(1.75/max);controls.current.zoom=1;controls.current.rotX=0;controls.current.rotY=0}
function addLoomis(root){const g=new THREE.Group();g.name='loomis_overlay';const mat=new THREE.LineBasicMaterial({color:0x7dd3fc,transparent:true,opacity:.9});const mat2=new THREE.MeshBasicMaterial({color:0xffffff,wireframe:true,transparent:true,opacity:.18});const sphere=new THREE.Mesh(new THREE.SphereGeometry(.52,48,24),mat2);sphere.scale.set(1,.96,.92);g.add(sphere);const makeRing=(rx,ry,rz,sx=1,sy=1)=>{const r=new THREE.Line(new THREE.BufferGeometry().setFromPoints(new THREE.EllipseCurve(0,0,.53*sx,.53*sy,0,Math.PI*2).getPoints(128)),mat);r.rotation.set(rx,ry,rz);g.add(r)};makeRing(Math.PI/2,0,0,1,.92);makeRing(0,Math.PI/2,0,.92,1);makeRing(0,0,0,1,.96);const eye=new THREE.Line(new THREE.BufferGeometry().setFromPoints([new THREE.Vector3(-.58,0,0),new THREE.Vector3(.58,0,0)]),mat);g.add(eye);const center=new THREE.Line(new THREE.BufferGeometry().setFromPoints([new THREE.Vector3(0,.55,0),new THREE.Vector3(0,-.75,0)]),mat);g.add(center);g.position.set(0,.1,.03);root.add(g)}
function loadModel(url){setErr('');setLoading('טוען מודל...');clearModel();new GLTFLoader().load(url,g=>{const root=g.scene;frame(root);addLoomis(root);modelRef.current=root;sceneRef.current.add(root);const ns=morphNames(root);setNames(ns);setValues({});setLoading('');},p=>{if(p.total)setLoading('טוען '+Math.round(p.loaded/p.total*100)+'%')},e=>{setErr('הטעינה נכשלה. נסה Upload GLB מתוך האייפון או רענון.');setLoading('')})}
function upload(e){const f=e.target.files?.[0];if(!f)return;const u=URL.createObjectURL(f);loadModel(u)}
function setMorph(n,v){setValues(x=>({...x,[n]:v}));applyMorph(modelRef.current,n,v)}
function reset(){names.forEach(n=>applyMorph(modelRef.current,n,0));setValues({})}
function preset(p){reset();const vals=PRESETS[p]||{};Object.entries(vals).forEach(([n,v])=>{applyMorph(modelRef.current,n,v)});setValues(vals)}
useEffect(()=>{const m=modelRef.current;if(!m)return;m.traverse(o=>{if(o.name==='loomis_overlay')o.visible=overlay;if(o.isMesh)o.material.wireframe=wire})},[overlay,wire]);
const filtered=useMemo(()=>names.filter(n=>tab==='viseme'?/viseme|mouth|jaw|tongue/i.test(n):tab==='eyes'?/eye|brow|cheek/i.test(n):true),[names,tab]);
return <div className="app"><main ref={mount} className="stage"/><section className="panel"><div className="grab"/><header><div><h1>Morph Head Studio</h1><p>{loading||err||`${names.length} morph targets נמצאו`}</p></div><label className="upload">Upload GLB<input type="file" accept=".glb,.gltf" onChange={upload}/></label></header>{err&&<div className="err">{err}</div>}<div className="toggles"><button onClick={()=>setOverlay(!overlay)} className={overlay?'on':''}>Loomis</button><button onClick={()=>setWire(!wire)} className={wire?'on':''}>Wire</button><button onClick={()=>preset('neutral')}>Reset</button></div><div className="presets">{Object.keys(PRESETS).map(p=><button key={p} onClick={()=>preset(p)}>{p}</button>)}</div><nav><button onClick={()=>setTab('morph')} className={tab==='morph'?'on':''}>All</button><button onClick={()=>setTab('eyes')} className={tab==='eyes'?'on':''}>Eyes</button><button onClick={()=>setTab('viseme')} className={tab==='viseme'?'on':''}>Mouth</button></nav><div className="sliders">{filtered.map(n=><label key={n}><span>{n}</span><input type="range" min="0" max="1" step="0.01" value={values[n]||0} onChange={e=>setMorph(n,parseFloat(e.target.value))}/></label>)}</div></section></div>}

createRoot(document.getElementById('root')).render(<App/>);